/**
 * System-level standard roles for EduTech College Management System.
 * Fully configurable, extensible, and cloneable per institution.
 */
export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  REGISTRAR = 'REGISTRAR',
  DEPUTY_REGISTRAR = 'DEPUTY_REGISTRAR',
  ADMISSIONS_OFFICER = 'ADMISSIONS_OFFICER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  ACADEMIC_ADMIN = 'ACADEMIC_ADMIN',
  DEAN = 'DEAN',
  HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT',
  EXAMINATION_OFFICER = 'EXAMINATION_OFFICER',
  LECTURER = 'LECTURER',
  COORDINATOR = 'COORDINATOR',
  LIBRARIAN = 'LIBRARIAN',
  HOSTEL_WARDEN = 'HOSTEL_WARDEN',
  ICT_ADMIN = 'ICT_ADMIN',
  HR_OFFICER = 'HR_OFFICER',
  PROCUREMENT_OFFICER = 'PROCUREMENT_OFFICER',
  STUDENT_AFFAIRS_OFFICER = 'STUDENT_AFFAIRS_OFFICER',
  COUNSELOR = 'COUNSELOR',
  SECURITY_OFFICER = 'SECURITY_OFFICER',
  PARENT_SPONSOR = 'PARENT_SPONSOR',
  STUDENT = 'STUDENT',
  APPLICANT = 'APPLICANT',
  ALUMNI = 'ALUMNI',
  AUDITOR = 'AUDITOR',
  EXECUTIVE = 'EXECUTIVE',
  HELPDESK_STAFF = 'HELPDESK_STAFF',
}

export enum ScopeType {
  GLOBAL = 'GLOBAL',
  CAMPUS = 'CAMPUS',
  FACULTY = 'FACULTY',
  DEPARTMENT = 'DEPARTMENT',
  PROGRAM = 'PROGRAM',
  COHORT = 'COHORT',
  SELF = 'SELF',
}
